# Hugo Configuration File.
baseURL = "https://wirehaiku.org/"
theme   = "wirehaiku"
title   = "Wire Haiku"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."
languageCode = "en-us"

[author]
name  = "Stephen Malone"
email = "mail@wirehaiku.org"

[frontmatter]
date = [":filename"]

[params]
author  = "Stephen Malone"
twitter = "https://twitter.com/wirehaiku"
donate  = "https://ko-fi.com/wirehaiku"
description = "Haiku about city life and modern nature, by Stephen Malone."
alert = ""
intro = """
<p>
    Hello and welcome to <strong>Wire Haiku</strong>: a journal of haiku poetry about city
    life and modern nature, written by Stephen Malone. You can
    <a href="/pages/about/">click here</a> to learn more about the site, check
    out the <a href="/pages/archives/">archives</a>, follow me on
    <a rel="me" href="https://stvmln.com/@stvmln">Mastodon</a> or just keep reading!
</p>
"""

menu = [
    ["Home",         "https://wirehaiku.org"],
    ["About",        "/pages/about/"],
    ["Archives",     "/pages/archives/"],
    ["Mastodon 🐘", "https://stvmln.com/@stvmln"],
    ["Support 💸",  "https://ko-fi.com/wirehaiku"],
]

[permalinks]
theme = "/theme/:slug/"
tags  = "/tag/:slug/"

[taxonomies]
theme = "theme"
tag   = "tags"

[markup.goldmark.extensions]
typographer = true
