# Hugo Configuration File.
baseURL = "https://wirehaiku.org/"
theme   = "wirehaiku"
title   = "Wire Haiku"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."
languageCode = "en-us"

[author]
name  = "Stephen Malone"
email = "mail@wirehaiku.org"

[frontmatter]
date = [":filename"]

[params]
author  = "Stephen Malone"
description = "Haiku about city life and modern nature, by Stephen Malone."
intro = """
Hello and welcome to <strong>Wire Haiku</strong>: a journal of haiku poetry about city life and modern nature, written by Stephen Malone. You can read the [about page](/pages/about/), check out the [archives](/posts/), or just keep on scrolling!
"""

footer = """
Powered by [Hugo](https://gohugo.io/), licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
"""

menu = [
    "<a href='/'>Home</a>",
    "<a href='/pages/about/'>About</a>",
    "<a href='/posts/'>Archives</a>",
    "<a href='/pages/cloud/'>Tag Cloud</a>",
    "<a href='https://mastodon.social/@stvmln' rel='me'>Mastodon</a>",
]

[permalinks]
theme = "/theme/:slug/"
tags  = "/tag/:slug/"

[taxonomies]
theme = "theme"
tag   = "tags"

[markup.goldmark.extensions]
typographer = true

[markup.goldmark.renderer]
unsafe = true
