# Hugo Configuration File.
baseURL = "https://wirehaiku.org/"
theme   = "wirehaiku"
title   = "Wire Haiku"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."
languageCode = "en-us"

[author]
name  = "Stephen Malone"
email = "mail@wirehaiku.org"

[frontmatter]
date = [":filename"]

[params]
author  = "Stephen Malone"
twitter = "https://twitter.com/wirehaiku"
donate  = "https://ko-fi.com/wirehaiku"
description = "Haiku about city life and modern nature, by Stephen Malone."
alert = ""
intro = """
Hello and welcome to **Wire Haiku**: a [journal of haiku poetry][1] about city
life and modern nature, written by Stephen Malone.

[1]: /pages/about/
"""

menu = [
    ["About",    "/pages/about/"],
    ["Archives", "/pages/archives/"],
    ["Compendium", "/pages/compendium"],
    ["Twitter",  "https://twitter.com/wirehaiku"],
    ["Support",   "https://ko-fi.com/wirehaiku"],
]

[permalinks]
theme = "/theme/:slug/"
tags  = "/tag/:slug/"

[taxonomies]
theme = "theme"
tag   = "tags"

[markup.goldmark.extensions]
typographer = true
