# Hugo Configuration File.
baseURL = "https://wirehaiku.org/"
theme   = "wirehaiku"
title   = "Wire Haiku"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."
languageCode = "en-us"

[author]
name  = "Stephen Malone"
email = "mail@wirehaiku.org"

[frontmatter]
date = [":filename"]

[params]
author  = "Stephen Malone"
description = "Haiku about city life and modern nature, by Stephen Malone."
intro = """
<p>
    Hello and welcome to <strong>Wire Haiku</strong>: a journal of haiku poetry about city
    life and modern nature, written by Stephen Malone. You can read the
    <a href="/pages/about/">about page</a>, check out the <a href="/posts/">archives</a>,
    or just keep on scrolling!
</p>
"""

footer = """
Powered by <a href="https://gohugo.io/">Hugo</a>,
licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>.
"""

menu = [
    "<a class='button' href='/'>Home</a>",
    "<a class='button' href='/pages/about/'>About</a>",
    "<a class='button' href='/posts/'>Archives</a>",
    "<a class='button' href='/pages/cloud/'>Tag Cloud</a>",
    "<a class='button' href='https://mastodon.social/@stvmln' rel='me'>Mastodon</a>",
]

[permalinks]
theme = "/theme/:slug/"
tags  = "/tag/:slug/"

[taxonomies]
theme = "theme"
tag   = "tags"

[markup.goldmark.extensions]
typographer = true

[markup.goldmark.renderer]
unsafe = true
