# Hugo Configuration File.
baseURL = "https://wirehaiku.org/"
theme   = "wirehaiku"
title   = "Wire Haiku"
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."

[author]
name  = "Stephen Malone"
email = "mail@wirehaiku.org"

[frontmatter]
date = [":filename"]

[params]
author  = "Stephen Malone"
twitter = "wirehaiku"
donate  = "https://ko-fi.com/wirehaiku"
description = "Haiku about city life and modern nature, by Stephen Malone."
intro = """
Hello and welcome to **Wire Haiku**, a journal of [haiku poetry][1] about city life and modern nature.

[1]: https://en.wikipedia.org/wiki/Haiku
"""

[permalinks]
categories = "/category/:slug/"
tags       = "/tag/:slug/"

[taxonomies]
category = "categories"
tag      = "tags"
